package ru.relex.pt.dto;

// Generated 11.02.2009 16:09:29 by Hibernate Tools 3.2.0.beta7

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;


/**
 * PwWorkType generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "PW_WORK_TYPE", uniqueConstraints = {})
public class PwWorkTypeDTO extends IdableDTO implements Serializable
{

    // Fields

    private BigDecimal workTypeId;

    private String name;

    private Set<PwWorkTimesDTO> pwWorkTimeses = new HashSet<PwWorkTimesDTO>(0);

    // Constructors

    /** default constructor */
    public PwWorkTypeDTO()
    {
    }

    /** minimal constructor */
    public PwWorkTypeDTO(BigDecimal workTypeId, String name)
    {
        this.workTypeId = workTypeId;
        this.name = name;
    }

    /** full constructor */
    public PwWorkTypeDTO(BigDecimal workTypeId, String name,
        Set<PwWorkTimesDTO> pwWorkTimeses)
    {
        this.workTypeId = workTypeId;
        this.name = name;
        this.pwWorkTimeses = pwWorkTimeses;
    }

    // Property accessors
    @Id
    @Column(name = "WORK_TYPE_ID", unique = true, nullable = false, insertable = true, updatable = true, precision = 22, scale = 0)
    public BigDecimal getWorkTypeId()
    {
        return this.workTypeId;
    }

    public void setWorkTypeId(BigDecimal workTypeId)
    {
        this.workTypeId = workTypeId;
    }

    @Column(name = "NAME", unique = false, nullable = false, insertable = true, updatable = true, length = 64)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @OneToMany(cascade = {CascadeType.REMOVE}, fetch = FetchType.LAZY, mappedBy = "pwWorkType")
    public Set<PwWorkTimesDTO> getPwWorkTimeses()
    {
        return this.pwWorkTimeses;
    }

    public void setPwWorkTimeses(Set<PwWorkTimesDTO> pwWorkTimeses)
    {
        this.pwWorkTimeses = pwWorkTimeses;
    }
    
    /**
     * Данный метод необходим для поддержки реализации интерфейса {@link Idable}.
     */
    @Transient
    @Override
    public BigDecimal getId()
    {
        return getWorkTypeId();
    }
}
